const AWS_EVENT = {
  CLOUDFRONT: 'CLOUDFRONT',
  COGNITO_SYNC: 'COGNITO_SYNC',
  DYNAMODB: 'DYNAMODB',
  KINESIS: 'KINESIS',
  KINESIS_FIREHOSE: 'KINESIS_FIREHOSE',
  S3: 'S3',
  SES: 'SES',
  SNS: 'SNS',
  SCHEDULED_EVENT: 'SCHEDULED_EVENT',
  APIGATEWAY_PROXY: 'APIGATEWAY_PROXY',
  UNKNOWN: 'UNKNOWN',
};
export default AWS_EVENT;
